name: build
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

jobs:
  boards:
    name: boards
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: Get board names
        id: get_boards
        run: echo "board_names=$(make board_names | tr '[:space:]' '\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
    outputs:
      board_names: ${{ steps.get_boards.outputs.board_names }}

  build:
    name: build
    runs-on: ubuntu-latest
    needs: boards
    container:
      image: ghcr.io/${{ github.repository }}:latest
    strategy:
      matrix:
        fw: ${{ fromJson(needs.boards.outputs.board_names) }}

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7


      - name: Build firmware
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          make -j4 fw_${{ matrix.fw }}

      - name: Publish firmware artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: binary_${{ matrix.fw }}
          path: build
  package:
    name: package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"

      - name: Download firmware artifact
        uses: actions/download-artifact@v4.1.8
        with:
          path: build
          merge-multiple: true

      - name: Package firmware
        run: |
          python package_firmware.py

      - name: Upload package artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: package
          path: package
          retention-days: 30

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: package

      - name: Tar up release artifacts
        run: tar -czf package.tar.gz package

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: package.tar.gz
